### ISSUE TITLE
bootstrap 기본 테마 기반으로 작성된 UI를 다른 테마 얹어서 시도해보기

### ISSUE THREAD

**Issue by malkoG** [malkoG/YiMattHong#28]
Tailwindcss도 daisyUI라는 컴포넌트라이브러리가 있는데, 이와 비슷한 것이 bootstrap에도 있지 않을까라는 생각이 들었음.
(무엇보다 기본 테마는 이쁘지 않음)

아래 댓글로 괜찮은 후보를 물색해볼 예정

**Comment by malkoG** [comment]
https://bootswatch.com/

**Comment by heeboy007** [comment]
https://startbootstrap.com/

**Comment by malkoG** [comment]
closed by #29
